from nginx:1.13-alpine
add api.saas.com.conf /etc/nginx/conf.d
add www.saas.com.conf /etc/nginx/conf.d
add os.saas.com.conf /etc/nginx/conf.d
add index.html /usr/share/nginx/html/index.html
user root
